name: Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check formatting
      # Run prettier in check mode (doesn't modify files)
      run: npx prettier --check "{src,test}/**/*.{ts,tsx}"
      
    - name: Format instructions (if check fails)
      if: ${{ failure() }}
      run: |
        echo "::error::Formatting issues detected. Run 'npm run format' locally to fix."
